### ISSUE TITLE
strange `coef` error

### ISSUE THREAD

**Issue by ArthurSpirling** [matthewjdenny/preptest#7]
Just updated to latest version of `quanteda` and it seems to break  version of `preText`.  In particular, 
```
preText_results <- preText(
  preprocessed_documents,
  dataset_name = "Some bills",
  distance_method = "cosine",
  num_comparisons = 20,
  verbose = FALSE)
```
yields
```
Error: 'coef' is not an exported object from 'namespace:quanteda'
```

**Comment by ArthurSpirling** [comment]
The data for this is as attached.
[hr_1.txt](https://github.com/matthewjdenny/preText/files/2177384/hr_1.txt)
[hr_2.txt](https://github.com/matthewjdenny/preText/files/2177385/hr_2.txt)
[hr_3.txt](https://github.com/matthewjdenny/preText/files/2177386/hr_3.txt)
[hr_4.txt](https://github.com/matthewjdenny/preText/files/2177387/hr_4.txt)
[hr_5.txt](https://github.com/matthewjdenny/preText/files/2177388/hr_5.txt)
[hr_7.txt](https://github.com/matthewjdenny/preText/files/2177389/hr_7.txt)
[hr_8.txt](https://github.com/matthewjdenny/preText/files/2177390/hr_8.txt)
[hr_9.txt](https://github.com/matthewjdenny/preText/files/2177391/hr_9.txt)
[hr_10.txt](https://github.com/matthewjdenny/preText/files/2177392/hr_10.txt)
[hr_11.txt](https://github.com/matthewjdenny/preText/files/2177393/hr_11.txt)
[hr_12.txt](https://github.com/matthewjdenny/preText/files/2177394/hr_12.txt)
[hr_14.txt](https://github.com/matthewjdenny/preText/files/2177395/hr_14.txt)
[hr_15.txt](https://github.com/matthewjdenny/preText/files/2177396/hr_15.txt)
[hr_16.txt](https://github.com/matthewjdenny/preText/files/2177397/hr_16.txt)
[hr_21.txt](https://github.com/matthewjdenny/preText/files/2177398/hr_21.txt)
[hr_22.txt](https://github.com/matthewjdenny/preText/files/2177399/hr_22.txt)
[hr_23.txt](https://github.com/matthewjdenny/preText/files/2177400/hr_23.txt)
[hr_24.txt](https://github.com/matthewjdenny/preText/files/2177401/hr_24.txt)
[hr_25.txt](https://github.com/matthewjdenny/preText/files/2177402/hr_25.txt)
[hr_26.txt](https://github.com/matthewjdenny/preText/files/2177403/hr_26.txt)
[hr_27.txt](https://github.com/matthewjdenny/preText/files/2177404/hr_27.txt)
[hr_28.txt](https://github.com/matthewjdenny/preText/files/2177405/hr_28.txt)
[hr_29.txt](https://github.com/matthewjdenny/preText/files/2177406/hr_29.txt)
[hr_30.txt](https://github.com/matthewjdenny/preText/files/2177407/hr_30.txt)

**Comment by ArthurSpirling** [comment]
And note that 
```
preprocessed_documents <- factorial_preprocessing(
  documents,
  use_ngrams = TRUE,
  infrequent_term_threshold = 0.2,
  verbose = FALSE)
```

works/looks fine for this data.

**Comment by ArthurSpirling** [comment]
Apologies, just reinstalled preText and quanteda.  Possibly old version? Seems to work now.  feel free to close now!

**Comment by matthewjdenny** [comment]
I think that was an issue with the previous version and the newest version of quanteda (or vice-versa), glad it resolved itself!
